name: Test and Audit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
        working-directory: election-system/frontend
      - run: npm test
        working-directory: election-system/frontend
      - run: npm audit --production
        working-directory: election-system/frontend