@startuml Election
class Election {
    ' -- vars --
	+[[mapping bytes32=>bool ]] registeredTokens
	+[[mapping bytes32=>bool ]] usedTokens
	+[[address]] admin
	+[[bool]] votingOpen
	+[[bool]] electionBegin
	+[[string]] electionTitle
	+[[EncryptedVote]] encryptedVotes
	+[[Candidate]] candidates
	+[[ElectionResult]] electionResults
        +[[ElectionDistrict]] electionDistricts
    ' -- methods --
	+**__constructor__**()
	+registerCandidate()
	+🔍getCandidates()
	+registerToken()
	+🔍isTokenValid()
	+markTokenUsed()
	+startVoting()
	+endVoting()
	+castEncryptedVote()
	+🔍getEncryptedVotes()
	+storeElectionResult()
	+🔍getElectionResults()
	+🔍getElectionStatus()
	+🔍getElectionTitle()
}



struct Candidate {
  name: string
  electionDistrict: uint
  votes: unint
}

struct ElectionDistrict {
  name: string
  number: uint
}

struct EncryptedVote {
  vote: Candidate
  electionDistrict: uint
}

struct ElectionResult {
  tally: string
  signiture: string
  timestamp: unint
  electionDistrict: uint
}

Election <|-- Candidate
Election <|-- ElectionResult
Election <|-- EncryptedVote
Candidate <|-- ElectionDistrict
ElectionResult <|-- ElectionDistrict
EncryptedVote <|-- ElectionDistrict
@enduml